### ISSUE TITLE
Use spacing as per WordPress coding standards

### ISSUE THREAD

**Issue by burhandodhy** [zackphilipps/zp-acf-snippets#1]
With all snippets, current output does not use spacing (for example):

the_field('field_name');

It would be great if the snippets followed WP coding standards and used spacing:

the_field( 'field_name' );

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage

**Comment by zoephilipps** [comment]
Thanks for that! I was not aware that that was the standard for spacing, makes sense why I see it everywhere now. It hurts my eyes and soul a little, but standards should be maintained. :) Should be good to go with version 0.4.0.
